# Code quality tooling configuration
[tool.ruff]
line-length = 120
target-version = "py311"
fix = true

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = ["D203", "D212", "COM812", "ISC001", "T201"]

#[tool.ruff.lint.per-file-ignores]
#"app.py" = ["PLR0913"] # Not relevant for Gradio
#"train.py" = ["PTH"] # Fix some other time
#"test_*.py" = ["S101"] # Allow assert in tests

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true